#!/bin/sh

bspc config focus_follows_pointer true

# middleclick also resizes corner
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_action3 resize_corner

bspc monitor $(bspc query -M) -d 1 2 3 4 5 6 7 8 9 10

